// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NftSaleDemo.Api.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NftSaleDemo.Api.Migrations
{
    [DbContext(typeof(NftSaleDemoContext))]
    partial class NftSaleDemoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NftSaleDemo.Api.Models.Nft", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("BaseCost")
                        .HasColumnType("bigint")
                        .HasColumnName("base_cost");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rarity");

                    b.Property<int>("StepCost")
                        .HasColumnType("integer")
                        .HasColumnName("step_cost");

                    b.Property<int>("StepQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("step_quantity");

                    b.HasKey("Id")
                        .HasName("pk_nfts");

                    b.ToTable("Nfts");
                });

            modelBuilder.Entity("NftSaleDemo.Api.Models.NftSale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("NftSaleStatus")
                        .HasColumnType("text")
                        .HasColumnName("nft_sale_status");

                    b.Property<string>("TransactionCbor")
                        .HasColumnType("text")
                        .HasColumnName("transaction_cbor");

                    b.Property<string>("TransactionResult")
                        .HasColumnType("text")
                        .HasColumnName("transaction_result");

                    b.HasKey("Id")
                        .HasName("pk_nft_sales");

                    b.ToTable("NftSales");
                });
#pragma warning restore 612, 618
        }
    }
}
